steps:
  - name: node:20.11.1
    entrypoint: npm
    args: ["install"]
  - name: node:20.11.1
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.yaml"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "api.yaml"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY