// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecondChair.Api.Entities;

#nullable disable

namespace SecondChair.Api.Migrations
{
    [DbContext(typeof(SecondChairContext))]
    partial class SecondChairContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecondChair.Api.Entities.Case", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cases", (string)null);
                });

            modelBuilder.Entity("SecondChair.Api.Entities.Juror", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<decimal?>("PositionX")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PositionY")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Selected")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stoplight")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.ToTable("Jurors", (string)null);
                });

            modelBuilder.Entity("SecondChair.Api.Entities.Case", b =>
                {
                    b.OwnsOne("SecondChair.Api.Entities.Case.Strikes#SecondChair.Api.Entities.Strikes", "Strikes", b1 =>
                        {
                            b1.Property<Guid>("CaseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Defendant")
                                .HasColumnType("int");

                            b1.Property<int>("Plaintiff")
                                .HasColumnType("int");

                            b1.Property<int>("Total")
                                .HasColumnType("int");

                            b1.HasKey("CaseId");

                            b1.ToTable("Cases", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaseId");
                        });

                    b.Navigation("Strikes");
                });

            modelBuilder.Entity("SecondChair.Api.Entities.Juror", b =>
                {
                    b.HasOne("SecondChair.Api.Entities.Case", "Case")
                        .WithMany("Jurors")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("SecondChair.Api.Entities.Case", b =>
                {
                    b.Navigation("Jurors");
                });
#pragma warning restore 612, 618
        }
    }
}
